### ISSUE TITLE
I can see a list of all talks/posters

### ISSUE THREAD

**Issue by MeenaFoerderer** [MeenaFoerderer/Capstone-project#1]
## Value proposition

**As a** user
**I want to** see all talks and posters listed,
**so that** I can have an overview of what is happening when and where.

## Description

![Image](https://user-images.githubusercontent.com/105375266/201886924-dd049dcc-d15c-4351-abfc-c6aada0dd119.png)

## Acceptance Criteria

- [ ] all talks and posters are displayed in a list
- [ ] each talk and poster list item displays the title, the author(s), the session, the time, and the room
- [ ] the talks and posters are sorted by session and time
- [ ] the list should have its own headline

## Tasks

- [ ] create dummy data as json file
- [ ] create a `TalkCard` component
> - [ ] title, author, session, time, and room as a prop
> - [ ] component test
- [ ] fetch dummy data and display in the `TalkCard` component
- [ ] display `TalkCard` component items in an unordered list

## Complexity

M
