### ISSUE TITLE
I can navigate between days

### ISSUE THREAD

**Issue by MeenaFoerderer** [MeenaFoerderer/Capstone-project#10]
## Value proposition

**As a** user
**I want to** be able to switch to the next day,
**so that** I can see which talks happen on which day.

## Description 

![Image](https://user-images.githubusercontent.com/105375266/203349205-764404bf-3cb1-4329-9be5-4020649bb20d.png)

## Acceptance criteria
- [ ] all talks that happen on one day are listed within that day
- [ ] the user can scroll up and down between the talks of one day
- [ ] on top of the talks list the days and the room are displayed
- [ ] the day, bottom nav bar, and room should remain in place while scrolling
- [ ] the room navigation buttons are placed beside the room
- [ ] the user can directly switch to the next day by clicking the respective day button
- [ ] the 'active' day is styled differently

## Tasks
- [ ] add more dummy data for two additional days
- [ ] create a component `DayNav` to built a day navigation
- [ ] create a page for each day in the pages directory
- [ ] display the respective talks in their days
- [ ] give the day navigation a fixed position
- [ ] make the buttons in the `DayNav` functional to navigate from day to day
- [ ] give the 'active' day extra styling to show which day the user is at
- [ ] change the styling and position of the room navigation and buttons

## Complexity Estimation
L
