### ISSUE TITLE
I can see details for each talk

### ISSUE THREAD

**Issue by MeenaFoerderer** [MeenaFoerderer/Capstone-project#11]
## Value proposition

**As a** user
**I want to** be able to see details of each talk,
**so that** I can decide which talk is interesting for me.

## Description 

![Image](https://user-images.githubusercontent.com/105375266/203523281-37086811-f321-45bd-a78a-6d361f4ae7be.png)

## Acceptance criteria
- [ ] each talk is linked to a details page
- [ ] the details page displays the talk information and abstract
- [ ] a 'close' button leads back to the talk list

## Tasks
- [ ] implement dynamic routing to display a details page for each talk
- [ ] in there, create a 'close' link styled as a button that leads back to the overview page

## Complexity Estimation
S
