### ISSUE TITLE
I can bookmark talks that I'm interested in

### ISSUE THREAD

**Issue by MeenaFoerderer** [MeenaFoerderer/Capstone-project#12]
## Value proposition
**As a** user
**I want to** be able to bookmark the talks I'm interested in
**so that** I see directly which talks I will attend.

## Description 

![Image](https://user-images.githubusercontent.com/105375266/205664029-b05432b6-ecf7-4383-9996-5afb83578d09.png)

## Acceptance criteria
- [x] the talk details page and each talk in the overview have a bookmark icon that can be toggled
- [x] activating the bookmark changes the style of the bookmark on both pages
- [x] bookmarked talks are displayed in a bookmarks list on a new page
- [x] removing the bookmark removes the talks from the bookmarks list
- [x] the bookmarks list can be accessed via a button on the landing page
- [x] the talk title on the overview page is limited in characters

## Tasks
- [x] modify the title preview in the overview so that the number of displayed characters is limited
- [x] add bookmark icons to each talk and to the details page
- [x] implement toggle functionality
- [x] add styling to the activated bookmark
- [x] save bookmarked talks to localStorage
- [x] create new page for bookmarks
- [x] get bookmarked talks from localStorage and display on bookmarks page
- [x] add a link to the landing page to access the bookmarks page

## Complexity Estimation
L

**Comment by marialitwa** [comment]
Very nice! It's all clear to me, nothing to improve from my side :)
