### ISSUE TITLE
I can add notes to each talk

### ISSUE THREAD

**Issue by MeenaFoerderer** [MeenaFoerderer/Capstone-project#13]
## Value proposition

**As a** user
**I want to** be able to add notes to talks
**so that** I have my notes directly associated to the respective talk.

## Description

![Image](https://user-images.githubusercontent.com/105375266/203595894-fe76e784-ba64-46a4-986f-a0cb618fdbc2.png)

## Acceptance criteria
- [ ] the talk details page has a button to add notes
- [ ] clicking the button opens a modal with an input form and a submit button
- [ ] the modal can be closed via a close or X button
- [ ] submitting a note closes the modal and adds the note to the details page

## Tasks
- [ ] add a button to add notes on the details page
- [ ] create a modal with a form for text input, a submit button, and a close button
- [ ] make the add notes button functional so that it opens up the modal
- [ ] save note entry to local storage when the submit button is clicked
- [ ] add extra functionality to the submit button to close the modal
- [ ] add functionality to the close button
- [ ] display the note from local storage in the details page

## Complexity Estimation
XL
