### ISSUE TITLE
I can switch between rooms

### ISSUE THREAD

**Issue by MeenaFoerderer** [MeenaFoerderer/Capstone-project#2]
## Value proposition

**As a** user
**I want to** see the talks listed for each room,
**so that** I can only see what is happening in each single room.

## Description

![Image](https://user-images.githubusercontent.com/105375266/201912242-87a2091f-1ca2-43c7-a075-8dfccbda1b14.png)

## Acceptance criteria
- [ ] all talks that are in the same room are listed on one page
- [ ] each room is displayed on a separate page
- [ ] in each room the talks are sorted by session
- [ ] in each session the talks are sorted by time
- [ ] on top of the talks list the respective room is displayed
- [ ] beside the room there are arrows to navigate between the rooms

## Tasks
- [ ] create a component `Room` for each room in the pages directory
- [ ] display respective `TalkCard` component items in their rooms
- [ ] create a component `RoomNav` which displays the room and buttons to navigate
- [ ] make the buttons functional to navigate from page to page

## Complexity Estimation
M

**Comment by MeenaFoerderer** [comment]
I made a few improvements. Previously I had the title of the conference being displayed in each room. I changed it to the respective room the user has navigated to. I also added a footer with two buttons to navigate between the rooms. I also put the respective session on top of the talks list instead of repeating it in each talk.

**Comment by WilhelmAlfke** [comment]
HI @MeenaFoerderer , i thought the original user story had been fine already but you managed to make it more tidy and clear with those small "additions"/changes. By avoiding repeated information and separating the navigation elements from the content you make it easier for the user to get their bearings. well done.
