### ISSUE TITLE
I have a landing page

### ISSUE THREAD

**Issue by MeenaFoerderer** [MeenaFoerderer/Capstone-project#5]
## Value proposition

**As a** user
**I want to** have a landing page,
**so that** I am welcomed to the app and can choose between conference info and the
schedule.

## Description

![Image](https://user-images.githubusercontent.com/105375266/202753446-3abc4d40-d6dc-4509-b1bc-c28906441dc8.png)

## Acceptance criteria
- [ ] the landing page shows a welcome message
- [ ] the landing page has two functional buttons to navigate to info or schedule
- [ ] there is an info page with a button that navigates back to the landing page
- [ ] the room pages have a button in the `Navbar` to navigate to the landing page

## Tasks
- [ ] create a landing and an info page in the pages directory
- [ ] add a welcome message and two functional buttons to the landing page
- [ ] add some dummy text and a functional button to the info page
- [ ] add a Home button to the NavBar of each of the room pages

## Complexity Estimation
S

**Comment by EugenMoser** [comment]
looks good
