### ISSUE TITLE
I can switch between rooms

### ISSUE THREAD

**Issue by MeenaFoerderer** [MeenaFoerderer/Capstone-project#6]
## Value proposition

**As a** user
**I want to** be able to switch to the next day,
**so that** I can see which talks happen on which day.

## Description 

![Image](https://user-images.githubusercontent.com/105375266/202912008-ec1e951c-dd98-4155-9cbe-392604c17d34.png)

## Acceptance criteria
- [ ] all talks that happen on one day are listed within that day
- [ ] the user can scroll up and down between the talks of one day
- [ ] on top of the talks list the days are displayed
- [ ] the day, bottom nav bar, and room should remain in place while scrolling
- [ ] the user can directly switch to the next day by clicking below on <day x>
- [ ] the 'active' day is highlighted

## Tasks
- [ ] add more dummy data for two additional days
- [ ] create a component `DayNav` to built a day navigation
- [ ] create a component `Day` for each day in the pages directory
- [ ] display the respective `TalkCard` component items in their days
- [ ] fix the day navigation so that it stays in place while scrolling
- [ ] make the buttons in the `DayNav` functional to navigate from day to day
- [ ] give the 'active' day extra styling to show which day the user is at

## Complexity Estimation
M
